spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true